import { Poppins } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const popins = Poppins({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "TalentGrid - A freelancing website",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()


  return (
    <html lang="en">
      <body className={popins.className}>
        <SessionProvider session={session}>
        <Navbar/>
        <div className="container mx-auto min-h-[87.8vh]">
            {children}
          </div>
        <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
